### ISSUE TITLE
Review/Recommend scenarios illustrating use of GitHub/Git in Library context

### ISSUE THREAD

**Issue by ndalyrose** [data-lessons/library-git-DEPRECATED#34]
I've drafted the following Library GitHub/Git use scenario (based on real life as well as the Audiences view https://software-carpentry.org/audience/), do folks think this works? Suggestions for more? 

You are a local librarian looking to create a crowdsourcing project allowing people to tag historical photographs. Your team looks at a few other crowdsourcing projects on the web and even though they all appear unique to each institution, they seem to have similar functionality and structure. Rather than build your version from scratch, you wish there was a way to just copy that version, and modify it to reflect your project. You notice the GitHub icon at the bottom of these pages. 

Related to #7

**Comment by drjwbaker** [comment]
(and based on the scenarios at https://software-carpentry.org/audience/)

**Comment by sanayahm** [comment]
Another scenario related to #7. Let me know what you think of this.

You manage a small library that used GitHub to clone certain aspects of your digital asset management system using a larger library's system. However, a few months later, you realized there were certain glitches that you wanted to address.

Using GitHub will allow you to trace back to what went wrong and when (since all edits are recorded). Since GitHub can be perceived as an 'archive' of changes, you can also trace the initial creator of the digital asset management system that you created and reach out to them for feedback.

**Comment by sanayahm** [comment]
@ndalyrose looks good!!!

**Comment by billmcmillin** [comment]
Excellent examples. I've been trying to think of an example that would appeal to users who are less familiar with coding. Would something like the following be helpful?

Multiple librarians editing metadata for a collection

A librarian has exported a spreadsheet of metadata from a repository for cleaning and editing. She's working with a group of librarians and students, so they need to make sure edits don't conflict. They also need to be able to undo any edits and preserve the original metadata. Once edits are complete, the whole group wants to review the changes before re-ingesting the spreadsheet of metadata into the repository. 

The team can choose to use Git by itself to track changes and resolve conflicts or they can choose to use GitHub to host the project so that users can collaborate and review changes on the Web. Git will preserve the original metadata as well as all edits. GitHub will facilitate discussion about what changes should be made, who should make them, and why.

**Comment by weaverbel** [comment]
I like this @billmcmillin - do you want to try to fork the file and add this scenario and then do a pull request, or do you want me to add it?

**Comment by billmcmillin** [comment]
Thanks @weaverbel. I'll fork it and submit a PR.

**Comment by weaverbel** [comment]
@sanayahm Are you going to write up your scenario or do you want a maintainer to add it?

**Comment by VickySteeves** [comment]
Is this issue still open or has it been resolved? Just wondering if I should add stuff from #7 & this thread to my PR to the git lesson.
