### ISSUE TITLE
All in One Page Not Working

### ISSUE THREAD

**Issue by norlab** [data-lessons/library-git-DEPRECATED#60]
Under the Episodes Menu: 'All in One (Beta)' link returns a 404

https://data-lessons.github.io/library-git/aio/

**Comment by weaverbel** [comment]
Hi @norlab I can't find this link to fix it - can you please tell me which file in episodes it appears in?

**Comment by norlab** [comment]
@weaverbel - if you view the lesson at: https://data-lessons.github.io/library-git/ and click on 'episodes', you will then see the option for 'all in one page (Beta)'.

**Comment by weaverbel** [comment]
Thanks @norlab - I am not sure how to fix this - I've had a quick look but am not sure how to remove or fix that link. Will ask @rgaiacs to have a look. Raniere, do you have any idea?

**Comment by rgaiacs** [comment]
> Under the Episodes Menu: 'All in One (Beta)' link returns a 404

This happens because the `aio.md` file is missing at https://github.com/data-lessons/library-git. You can run https://github.com/data-lessons/library-git/blob/gh-pages/bin/lesson_initialize.py to create the [`aio.md`](https://github.com/data-lessons/library-git/blob/gh-pages/bin/lesson_initialize.py#L281) file. Be careful when running the Python script because it will overwrite some of other files, e.g. [`index.md`](https://github.com/data-lessons/library-git/blob/gh-pages/index.md) so you probably want to only commit the changes on `aio.md` and discard the other changes (e.g. usign `git checkout -f HEAD`).

https://github.com/swcarpentry/lesson-example/pull/130 and https://github.com/swcarpentry/lesson-example/pull/127 will avoid this type of the problem in the future.

**Comment by drjwbaker** [comment]
@rgaiacs Thanks! I think this crept into one of our template mergers without being fully implemented.

**Comment by rgaiacs** [comment]
> I think this crept into one of our template mergers without being fully implemented.

Yes. https://github.com/swcarpentry/styles/releases/tag/v9.2.0 has a upgrade note. :-( I hate this type of note. I used https://github.com/swcarpentry/infra-lessons to update the Software Carpentry lessons but I had to make small changes to accommodate v9.2.0.
